inherit: base.yaml
checkpoint: /home/user/Desktop/aryan/aryan/ckpt_official_smolvla_libero
output_dir: results/official_base/goal
suite: libero_goal
episode_length: 300
n_action_steps: 1
record:
  enabled: false
